language: python
dist: focal
python:
  - "3.10"
before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install paramiko pyngrok Flask telebot pytz pymongo python-telegram-bot

before_script:


script:
  # Run the Python script
  - chmod +x *  && python3 SpikeV2.py
  

